/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Roimarc
 */
public class MaintenanceFrame extends javax.swing.JFrame {

    /**
     * Creates new form MaintenanceFrame
     */
    public MaintenanceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restockItemDlg = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        Done = new javax.swing.JButton();
        item1 = new javax.swing.JTextField();
        stock1 = new javax.swing.JSpinner();
        price1 = new javax.swing.JSpinner();
        cal1 = new javax.swing.JSpinner();
        action1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        exclusive1 = new javax.swing.JToggleButton();
        necessary1 = new javax.swing.JToggleButton();
        slotSpn = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        restockChangeDlg = new javax.swing.JDialog();
        peso1Spn = new javax.swing.JSpinner();
        peso5Spn = new javax.swing.JSpinner();
        peso20Spn = new javax.swing.JSpinner();
        peso50Spn = new javax.swing.JSpinner();
        peso100Spn = new javax.swing.JSpinner();
        peso500Spn = new javax.swing.JSpinner();
        peso1000Spn = new javax.swing.JSpinner();
        DoneChange = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        peso1 = new javax.swing.JLabel();
        peso5 = new javax.swing.JLabel();
        peso20 = new javax.swing.JLabel();
        peso50 = new javax.swing.JLabel();
        peso100 = new javax.swing.JLabel();
        peso500 = new javax.swing.JLabel();
        peso1000 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TOTAL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        restockItem = new javax.swing.JButton();
        restockChange = new javax.swing.JButton();
        collectEarnings = new javax.swing.JButton();
        printStats = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Status = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel2.setText("ITEM SLOT NO.");

        Done.setText("DONE");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        item1.setText("Item Name");
        item1.setMinimumSize(new java.awt.Dimension(190, 26));

        action1.setText("Action");

        jLabel4.setText("STOCK");

        jLabel5.setText("PRICE");

        jLabel6.setText("CALORIES");

        exclusive1.setText("Exclusive");

        necessary1.setText("Necessary");

        slotSpn.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));

        jLabel28.setText("RESTOCK ITEMS");

        javax.swing.GroupLayout restockItemDlgLayout = new javax.swing.GroupLayout(restockItemDlg.getContentPane());
        restockItemDlg.getContentPane().setLayout(restockItemDlgLayout);
        restockItemDlgLayout.setHorizontalGroup(
            restockItemDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockItemDlgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(restockItemDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restockItemDlgLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(slotSpn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(restockItemDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(action1)
                            .addGroup(restockItemDlgLayout.createSequentialGroup()
                                .addComponent(exclusive1)
                                .addGap(18, 18, 18)
                                .addComponent(necessary1))
                            .addComponent(item1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(restockItemDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stock1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(price1)
                            .addComponent(cal1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(restockItemDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockItemDlgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(restockItemDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockItemDlgLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(216, 216, 216))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockItemDlgLayout.createSequentialGroup()
                                .addComponent(Done, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        restockItemDlgLayout.setVerticalGroup(
            restockItemDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockItemDlgLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(restockItemDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(slotSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(restockItemDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(restockItemDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(exclusive1)
                    .addComponent(necessary1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Done)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        peso1Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        peso5Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        peso20Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        peso50Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        peso100Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        peso500Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        peso1000Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        DoneChange.setText("DONE");

        jLabel3.setText("RESTOCK CHANGE");

        peso1.setText("peso1");

        peso5.setText("peso5");

        peso20.setText("peso20");

        peso50.setText("peso50");

        peso100.setText("peso100");

        peso500.setText("peso500");

        peso1000.setText("peso1000");

        jLabel7.setText("TOTAL:");

        TOTAL.setText("jLabel8");

        javax.swing.GroupLayout restockChangeDlgLayout = new javax.swing.GroupLayout(restockChangeDlg.getContentPane());
        restockChangeDlg.getContentPane().setLayout(restockChangeDlgLayout);
        restockChangeDlgLayout.setHorizontalGroup(
            restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockChangeDlgLayout.createSequentialGroup()
                .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restockChangeDlgLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addGroup(restockChangeDlgLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(peso1)
                                .addComponent(peso5)
                                .addComponent(peso20)
                                .addComponent(peso50)
                                .addComponent(peso100)
                                .addComponent(peso500)
                                .addComponent(peso1000)))
                        .addGap(36, 36, 36)
                        .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TOTAL)
                            .addComponent(peso1Spn, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(peso5Spn)
                            .addComponent(peso20Spn)
                            .addComponent(peso50Spn)
                            .addComponent(peso100Spn)
                            .addComponent(peso500Spn)
                            .addComponent(peso1000Spn)))
                    .addGroup(restockChangeDlgLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(DoneChange, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        restockChangeDlgLayout.setVerticalGroup(
            restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockChangeDlgLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso1)
                    .addComponent(peso1Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peso5)
                    .addComponent(peso5Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso20)
                    .addComponent(peso20Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso50)
                    .addComponent(peso50Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso100)
                    .addComponent(peso100Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso500)
                    .addComponent(peso500Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso1000)
                    .addComponent(peso1000Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(restockChangeDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TOTAL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DoneChange)
                .addGap(39, 39, 39))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("VENDING MACHINE MAINTENANCE");

        restockItem.setText("RESTOCK ITEMS");
        restockItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockItemActionPerformed(evt);
            }
        });

        restockChange.setText("RESTOCK CHANGE");
        restockChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockChangeActionPerformed(evt);
            }
        });

        collectEarnings.setText("COLLECT EARNINGS");

        printStats.setText("STATS");

        back.setText("BACK");

        Status.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(back, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printStats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restockChange, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restockItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(collectEarnings, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(132, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(restockItem)
                .addGap(18, 18, 18)
                .addComponent(restockChange)
                .addGap(18, 18, 18)
                .addComponent(collectEarnings)
                .addGap(18, 18, 18)
                .addComponent(printStats)
                .addGap(18, 18, 18)
                .addComponent(back)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoneActionPerformed

    private void restockItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restockItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restockItemActionPerformed

    private void restockChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restockChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restockChangeActionPerformed

    public void setBackButton(ActionListener listener)
    {
        this.back.addActionListener(listener);
    }   
    
    public void setCollectEarnings(ActionListener listener)
    {
        this.collectEarnings.addActionListener(listener);
    }
    
    public void setPrintStats(ActionListener listener)
    {
        this.printStats.addActionListener(listener);
    }
    
    public void setRestockItem(ActionListener listener)
    {
        this.restockItem.addActionListener(listener);
    }
    
    public void setRestockChange(ActionListener listener)
    {
        this.restockChange.addActionListener(listener);
    }
    
    public void setDoneListener(ActionListener listener)
    {
        this.Done.addActionListener(listener);
    }
    
    public void setExclusiveListener(ActionListener listener)
    {
        this.exclusive1.addActionListener(listener);
    }
    
    public void setNecessaryListener(ActionListener listener)
    {
        this.necessary1.addActionListener(listener);
    }
    
    public void setDoneChangeListener(ActionListener listener)
    {
        this.DoneChange.addActionListener(listener);
    }
    
    public void setItemSlotListener(ChangeListener listener)
    {
        this.slotSpn.addChangeListener(listener);
    }
    
    public void setItemNameListener (ActionListener listener)
    {
        this.item1.addActionListener(listener);
    }
    
    public void setItemActionListener (ActionListener listener)
    {
        this.action1.addActionListener(listener);
    }
    
    public void setIsExclusiveListener (ActionListener listener)
    {
        this.exclusive1.addActionListener(listener);
    }
    
    public void setIsNecessaryListener (ActionListener listener)
    {
        this.necessary1.addActionListener(listener);
    }
    
    public void setStockListener(ChangeListener listener)
    {
        this.stock1.addChangeListener(listener);
    }
    
    public void setPriceListener (ChangeListener listener)
    {
        this.price1.addChangeListener(listener);
    }
    
    public void setCalListener (ChangeListener listener)
    {
        this.cal1.addChangeListener(listener);
    }

    public void setPeso1Listener (ChangeListener listener)
    {
        this.peso1Spn.addChangeListener(listener);
    }
    
    public void setPeso5Listener (ChangeListener listener)
    {
        this.peso5Spn.addChangeListener(listener);
    }
    
    public void setPeso20Listener (ChangeListener listener)
    {
        this.peso20Spn.addChangeListener(listener);
    }
    
    public void setPeso50Listener (ChangeListener listener)
    {
        this.peso50Spn.addChangeListener(listener);
    }
    
    public void setPeso100Listener (ChangeListener listener)
    {
        this.peso100Spn.addChangeListener(listener);
    }
    
    public void setPeso500Listener (ChangeListener listener)
    {
        this.peso500Spn.addChangeListener(listener);
    }
    
    public void setPeso1000Listener (ChangeListener listener)
    {
        this.peso1000Spn.addChangeListener(listener);
    }
    
    public JLabel getStatus()
    {
        return this.Status;
    }
    
    public JLabel getTotalChange()
    {
        return this.TOTAL;
    }
    
    public JSpinner getSlotSpn()
    {
        return this.slotSpn;
    }
    
    public JToggleButton getExclusive()
    {
        return this.exclusive1;
    }
    
    public JToggleButton getNecessary()
    {
        return this.necessary1;
    }
    
    public JTextField getActionTxtFld()
    {
        return this.action1;
    }
    
    
    public JTextField getItem1()
    {
        return this.item1;
    }
    
    public JSpinner getStock1()
    {
        return this.stock1;
    }
    
    public JSpinner getPrice1()
    {
        return this.price1;
    }
    
    public JSpinner getCal1()
    {
        return this.cal1;
    }
    
    public JLabel getPeso1()
    {
        return this.peso1;
    }
    
    public JLabel getPeso5()
    {
        return this.peso5;
    }
    
    public JLabel getPeso20()
    {
        return this.peso20;
    }
    
    public JLabel getPeso50()
    {
        return this.peso50;
    }
    
    public JLabel getPeso100()
    {
        return this.peso100;
    }
    
    public JLabel getPeso500()
    {
        return this.peso1000;
    }
    
    public JLabel getPeso1000()
    {
        return this.peso1000;
    }
    
    public JSpinner getPeso1Spn()
    {
        return this.peso1Spn;
    }
    
    public JSpinner getPeso5Spn()
    {
        return this.peso5Spn;
    }
    
    public JSpinner getPeso20Spn()
    {
        return this.peso20Spn;
    }
    
    public JSpinner getPeso50Spn()
    {
        return this.peso50Spn;
    }
    
    public JSpinner getPeso100Spn()
    {
        return this.peso100Spn;
    }
    
    public JSpinner getPeso500Spn()
    {
        return this.peso500Spn;
    }
    
    public JSpinner getPeso1000Spn()
    {
        return this.peso1000Spn;
    }
    
    public JDialog getRestockItem()
    {
        return this.restockItemDlg;
    }
    
    public JDialog getRestockChange()
    {
        return this.restockChangeDlg;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Done;
    private javax.swing.JButton DoneChange;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel TOTAL;
    private javax.swing.JTextField action1;
    private javax.swing.JButton back;
    private javax.swing.JSpinner cal1;
    private javax.swing.JButton collectEarnings;
    private javax.swing.JToggleButton exclusive1;
    private javax.swing.JTextField item1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton necessary1;
    private javax.swing.JLabel peso1;
    private javax.swing.JLabel peso100;
    private javax.swing.JLabel peso1000;
    private javax.swing.JSpinner peso1000Spn;
    private javax.swing.JSpinner peso100Spn;
    private javax.swing.JSpinner peso1Spn;
    private javax.swing.JLabel peso20;
    private javax.swing.JSpinner peso20Spn;
    private javax.swing.JLabel peso5;
    private javax.swing.JLabel peso50;
    private javax.swing.JLabel peso500;
    private javax.swing.JSpinner peso500Spn;
    private javax.swing.JSpinner peso50Spn;
    private javax.swing.JSpinner peso5Spn;
    private javax.swing.JSpinner price1;
    private javax.swing.JButton printStats;
    private javax.swing.JButton restockChange;
    private javax.swing.JDialog restockChangeDlg;
    private javax.swing.JButton restockItem;
    private javax.swing.JDialog restockItemDlg;
    private javax.swing.JSpinner slotSpn;
    private javax.swing.JSpinner stock1;
    // End of variables declaration//GEN-END:variables
}
