/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextPane;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Roimarc
 */
public class VendingMachineFrame extends javax.swing.JFrame {

    /**
     * Creates new form VendingMachineFrame
     */
    public VendingMachineFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NoChangeError = new javax.swing.JDialog();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NotEnoughPaymentError = new javax.swing.JDialog();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ItemDispensedMsg = new javax.swing.JDialog();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Receipt = new javax.swing.JLabel();
        Receipt1 = new javax.swing.JLabel();
        item1 = new javax.swing.JPanel();
        item1Name = new javax.swing.JLabel();
        item1Price = new javax.swing.JLabel();
        item1Cal = new javax.swing.JLabel();
        item2 = new javax.swing.JPanel();
        item2Name = new javax.swing.JLabel();
        item2Price = new javax.swing.JLabel();
        item2Cal = new javax.swing.JLabel();
        item3 = new javax.swing.JPanel();
        item3Name = new javax.swing.JLabel();
        item3Price = new javax.swing.JLabel();
        item3Cal = new javax.swing.JLabel();
        item4 = new javax.swing.JPanel();
        item4Name = new javax.swing.JLabel();
        item4Price = new javax.swing.JLabel();
        item4Cal = new javax.swing.JLabel();
        item5 = new javax.swing.JPanel();
        item5Name = new javax.swing.JLabel();
        item5Price = new javax.swing.JLabel();
        item5Cal = new javax.swing.JLabel();
        item6 = new javax.swing.JPanel();
        item6Name = new javax.swing.JLabel();
        item6Price = new javax.swing.JLabel();
        item6Cal = new javax.swing.JLabel();
        item7 = new javax.swing.JPanel();
        item7Name = new javax.swing.JLabel();
        item7Price = new javax.swing.JLabel();
        item7Cal = new javax.swing.JLabel();
        item8 = new javax.swing.JPanel();
        item8Name = new javax.swing.JLabel();
        item8Price = new javax.swing.JLabel();
        item8Cal = new javax.swing.JLabel();
        buy1 = new javax.swing.JButton();
        buy2 = new javax.swing.JButton();
        buy3 = new javax.swing.JButton();
        buy4 = new javax.swing.JButton();
        buy5 = new javax.swing.JButton();
        buy6 = new javax.swing.JButton();
        buy7 = new javax.swing.JButton();
        buy8 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        confirm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Peso1Spn = new javax.swing.JSpinner();
        Peso5Spn = new javax.swing.JSpinner();
        Peso20Spn = new javax.swing.JSpinner();
        Peso50Spn = new javax.swing.JSpinner();
        Peso100Spn = new javax.swing.JSpinner();
        Peso500Spn = new javax.swing.JSpinner();
        Peso1000Spn = new javax.swing.JSpinner();
        TotalCostLbl = new javax.swing.JLabel();
        TotalPaymentLbl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        orderHistory = new javax.swing.JLabel();
        vmName = new javax.swing.JLabel();
        ordertxt = new javax.swing.JLabel();
        orderLbl = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Sorry. We do not have enough change :(");

        jButton1.setText("OK :(");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NoChangeErrorLayout = new javax.swing.GroupLayout(NoChangeError.getContentPane());
        NoChangeError.getContentPane().setLayout(NoChangeErrorLayout);
        NoChangeErrorLayout.setHorizontalGroup(
            NoChangeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoChangeErrorLayout.createSequentialGroup()
                .addGroup(NoChangeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NoChangeErrorLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton1))
                    .addGroup(NoChangeErrorLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        NoChangeErrorLayout.setVerticalGroup(
            NoChangeErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoChangeErrorLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("YOU DO NOT HAVE ENOUGH PAYMENT!");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NotEnoughPaymentErrorLayout = new javax.swing.GroupLayout(NotEnoughPaymentError.getContentPane());
        NotEnoughPaymentError.getContentPane().setLayout(NotEnoughPaymentErrorLayout);
        NotEnoughPaymentErrorLayout.setHorizontalGroup(
            NotEnoughPaymentErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotEnoughPaymentErrorLayout.createSequentialGroup()
                .addGroup(NotEnoughPaymentErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NotEnoughPaymentErrorLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton2))
                    .addGroup(NotEnoughPaymentErrorLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        NotEnoughPaymentErrorLayout.setVerticalGroup(
            NotEnoughPaymentErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotEnoughPaymentErrorLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("RECEIPT");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton3.setText("THANK YOU");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Receipt.setText("jLabel4");
        Receipt.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Receipt.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Receipt1.setText("TOTAL CALORIES: ");
        Receipt1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Receipt1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout ItemDispensedMsgLayout = new javax.swing.GroupLayout(ItemDispensedMsg.getContentPane());
        ItemDispensedMsg.getContentPane().setLayout(ItemDispensedMsgLayout);
        ItemDispensedMsgLayout.setHorizontalGroup(
            ItemDispensedMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemDispensedMsgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(172, 172, 172))
            .addGroup(ItemDispensedMsgLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ItemDispensedMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Receipt1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ItemDispensedMsgLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ItemDispensedMsgLayout.setVerticalGroup(
            ItemDispensedMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemDispensedMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Receipt1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vending Machine");
        setMinimumSize(new java.awt.Dimension(400, 800));

        item1.setBackground(new java.awt.Color(0, 0, 0));
        item1.setMaximumSize(new java.awt.Dimension(200, 91));
        item1.setPreferredSize(new java.awt.Dimension(200, 91));

        item1Name.setForeground(new java.awt.Color(255, 255, 255));
        item1Name.setText("ITEM");

        item1Price.setForeground(new java.awt.Color(255, 255, 255));
        item1Price.setText("PRICE:");

        item1Cal.setForeground(new java.awt.Color(255, 255, 255));
        item1Cal.setText("CAL:");

        javax.swing.GroupLayout item1Layout = new javax.swing.GroupLayout(item1);
        item1.setLayout(item1Layout);
        item1Layout.setHorizontalGroup(
            item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item1Name)
                    .addComponent(item1Cal)
                    .addComponent(item1Price))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        item1Layout.setVerticalGroup(
            item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item1Name)
                .addGap(25, 25, 25)
                .addComponent(item1Price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item1Cal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        item2.setBackground(new java.awt.Color(0, 0, 0));
        item2.setMaximumSize(new java.awt.Dimension(200, 91));
        item2.setPreferredSize(new java.awt.Dimension(200, 91));

        item2Name.setForeground(new java.awt.Color(255, 255, 255));
        item2Name.setText("ITEM");

        item2Price.setForeground(new java.awt.Color(255, 255, 255));
        item2Price.setText("PRICE:");

        item2Cal.setForeground(new java.awt.Color(255, 255, 255));
        item2Cal.setText("CAL:");

        javax.swing.GroupLayout item2Layout = new javax.swing.GroupLayout(item2);
        item2.setLayout(item2Layout);
        item2Layout.setHorizontalGroup(
            item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item2Name)
                    .addComponent(item2Cal)
                    .addComponent(item2Price))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        item2Layout.setVerticalGroup(
            item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item2Name)
                .addGap(25, 25, 25)
                .addComponent(item2Price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item2Cal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        item3.setBackground(new java.awt.Color(0, 0, 0));
        item3.setMaximumSize(new java.awt.Dimension(200, 91));
        item3.setPreferredSize(new java.awt.Dimension(200, 91));

        item3Name.setForeground(new java.awt.Color(255, 255, 255));
        item3Name.setText("ITEM");

        item3Price.setForeground(new java.awt.Color(255, 255, 255));
        item3Price.setText("PRICE:");

        item3Cal.setForeground(new java.awt.Color(255, 255, 255));
        item3Cal.setText("CAL:");

        javax.swing.GroupLayout item3Layout = new javax.swing.GroupLayout(item3);
        item3.setLayout(item3Layout);
        item3Layout.setHorizontalGroup(
            item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item3Name)
                    .addComponent(item3Cal)
                    .addComponent(item3Price))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        item3Layout.setVerticalGroup(
            item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item3Name)
                .addGap(25, 25, 25)
                .addComponent(item3Price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item3Cal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        item4.setBackground(new java.awt.Color(0, 0, 0));
        item4.setMaximumSize(new java.awt.Dimension(200, 91));

        item4Name.setForeground(new java.awt.Color(255, 255, 255));
        item4Name.setText("ITEM");

        item4Price.setForeground(new java.awt.Color(255, 255, 255));
        item4Price.setText("PRICE:");

        item4Cal.setForeground(new java.awt.Color(255, 255, 255));
        item4Cal.setText("CAL:");

        javax.swing.GroupLayout item4Layout = new javax.swing.GroupLayout(item4);
        item4.setLayout(item4Layout);
        item4Layout.setHorizontalGroup(
            item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item4Name)
                    .addComponent(item4Cal)
                    .addComponent(item4Price))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        item4Layout.setVerticalGroup(
            item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item4Name)
                .addGap(25, 25, 25)
                .addComponent(item4Price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item4Cal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        item5.setBackground(new java.awt.Color(0, 0, 0));
        item5.setMaximumSize(new java.awt.Dimension(200, 91));

        item5Name.setForeground(new java.awt.Color(255, 255, 255));
        item5Name.setText("ITEM");

        item5Price.setForeground(new java.awt.Color(255, 255, 255));
        item5Price.setText("PRICE:");

        item5Cal.setForeground(new java.awt.Color(255, 255, 255));
        item5Cal.setText("CAL:");

        javax.swing.GroupLayout item5Layout = new javax.swing.GroupLayout(item5);
        item5.setLayout(item5Layout);
        item5Layout.setHorizontalGroup(
            item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item5Name)
                    .addComponent(item5Cal)
                    .addComponent(item5Price))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        item5Layout.setVerticalGroup(
            item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item5Name)
                .addGap(25, 25, 25)
                .addComponent(item5Price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item5Cal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        item6.setBackground(new java.awt.Color(0, 0, 0));
        item6.setMaximumSize(new java.awt.Dimension(200, 91));
        item6.setPreferredSize(new java.awt.Dimension(200, 91));

        item6Name.setForeground(new java.awt.Color(255, 255, 255));
        item6Name.setText("ITEM");

        item6Price.setForeground(new java.awt.Color(255, 255, 255));
        item6Price.setText("PRICE:");

        item6Cal.setForeground(new java.awt.Color(255, 255, 255));
        item6Cal.setText("CAL:");

        javax.swing.GroupLayout item6Layout = new javax.swing.GroupLayout(item6);
        item6.setLayout(item6Layout);
        item6Layout.setHorizontalGroup(
            item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item6Name)
                    .addComponent(item6Cal)
                    .addComponent(item6Price))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        item6Layout.setVerticalGroup(
            item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item6Name)
                .addGap(25, 25, 25)
                .addComponent(item6Price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item6Cal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        item7.setBackground(new java.awt.Color(0, 0, 0));
        item7.setMaximumSize(new java.awt.Dimension(200, 91));

        item7Name.setForeground(new java.awt.Color(255, 255, 255));
        item7Name.setText("ITEM");

        item7Price.setForeground(new java.awt.Color(255, 255, 255));
        item7Price.setText("PRICE:");

        item7Cal.setForeground(new java.awt.Color(255, 255, 255));
        item7Cal.setText("CAL:");

        javax.swing.GroupLayout item7Layout = new javax.swing.GroupLayout(item7);
        item7.setLayout(item7Layout);
        item7Layout.setHorizontalGroup(
            item7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(item7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item7Name)
                    .addComponent(item7Cal)
                    .addComponent(item7Price))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        item7Layout.setVerticalGroup(
            item7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item7Name)
                .addGap(25, 25, 25)
                .addComponent(item7Price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item7Cal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        item8.setBackground(new java.awt.Color(0, 0, 0));
        item8.setMaximumSize(new java.awt.Dimension(200, 91));
        item8.setPreferredSize(new java.awt.Dimension(200, 91));

        item8Name.setForeground(new java.awt.Color(255, 255, 255));
        item8Name.setText("ITEM");

        item8Price.setForeground(new java.awt.Color(255, 255, 255));
        item8Price.setText("PRICE:");

        item8Cal.setForeground(new java.awt.Color(255, 255, 255));
        item8Cal.setText("CAL:");

        javax.swing.GroupLayout item8Layout = new javax.swing.GroupLayout(item8);
        item8.setLayout(item8Layout);
        item8Layout.setHorizontalGroup(
            item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item8Name)
                    .addComponent(item8Cal)
                    .addComponent(item8Price))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        item8Layout.setVerticalGroup(
            item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item8Name)
                .addGap(25, 25, 25)
                .addComponent(item8Price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item8Cal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buy1.setText("BUY");
        buy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy1ActionPerformed(evt);
            }
        });

        buy2.setText("BUY");
        buy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy2ActionPerformed(evt);
            }
        });

        buy3.setText("BUY");

        buy4.setText("BUY");
        buy4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy4ActionPerformed(evt);
            }
        });

        buy5.setText("BUY");

        buy6.setText("BUY");

        buy7.setText("BUY");

        buy8.setText("BUY");

        confirm.setText("CONFIRM");

        cancel.setText("CANCEL TRANSACTION");
        cancel.setEnabled(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PAYMENT");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("1 PHP");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("5 PHP");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("20 PHP");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("50 PHP");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("100 PHP");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("1000 PHP");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("500 PHP");

        Peso1Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Peso1Spn.setFocusTraversalPolicyProvider(true);

        Peso5Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        Peso20Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        Peso50Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        Peso100Spn.setModel(new javax.swing.SpinnerNumberModel());

        Peso500Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        Peso1000Spn.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        TotalCostLbl.setForeground(new java.awt.Color(255, 255, 255));
        TotalCostLbl.setText("COST: ");

        TotalPaymentLbl.setForeground(new java.awt.Color(255, 255, 255));
        TotalPaymentLbl.setText("PAYMENT: ");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ORDER HISTORY");

        orderHistory.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(orderHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(74, 74, 74))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalPaymentLbl)
                                    .addComponent(TotalCostLbl))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Peso100Spn)
                            .addComponent(Peso500Spn)
                            .addComponent(Peso5Spn)
                            .addComponent(Peso1Spn)
                            .addComponent(Peso20Spn)
                            .addComponent(Peso50Spn)
                            .addComponent(Peso1000Spn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Peso1Spn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Peso5Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(Peso20Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Peso50Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Peso100Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Peso500Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Peso1000Spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TotalCostLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalPaymentLbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        vmName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vmName.setText("VENDING MACHINE");
        vmName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ordertxt.setText("ORDER: ");

        BackButton.setText("BACK TO MAIN MENU");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(buy1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(181, 181, 181)
                                        .addComponent(buy2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(buy5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(182, 182, 182)
                                        .addComponent(buy6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(71, 71, 71)
                                                    .addComponent(buy3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(37, 37, 37)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(item4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(item2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(buy4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(65, 65, 65))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(item6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(item7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(buy7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(buy8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(66, 66, 66))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(item8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(vmName)))
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(ordertxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(vmName)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(item2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buy1)
                            .addComponent(buy2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(item4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buy4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buy3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item6, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(item5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buy6)
                            .addComponent(buy5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item8, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(item7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buy8)
                            .addComponent(buy7))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirm)
                            .addComponent(cancel))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ordertxt)
                                .addComponent(BackButton)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void buy4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buy4ActionPerformed

    private void buy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buy1ActionPerformed

    private void buy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buy2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.NoChangeError.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.NotEnoughPaymentError.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.ItemDispensedMsg.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    public void setBackButtonListener(ActionListener listener)
    {
        this.BackButton.addActionListener(listener);
    }
    
    public void setPeso1Spinner(ChangeListener listener)
    {
        this.Peso1Spn.addChangeListener(listener);
    }
    
    public void setPeso5Spinner(ChangeListener listener)
    {
        this.Peso5Spn.addChangeListener(listener);
    }
    
    public void setPeso20Spinner(ChangeListener listener)
    {
        this.Peso20Spn.addChangeListener(listener);
    }
    
    public void setPeso50Spinner(ChangeListener listener)
    {
        this.Peso50Spn.addChangeListener(listener);
    }
    
    public void setPeso100Spinner(ChangeListener listener)
    {
        this.Peso100Spn.addChangeListener(listener);
    }
    
    public void setPeso500Spinner(ChangeListener listener)
    {
        this.Peso500Spn.addChangeListener(listener);
    }
    
    public void setPeso1000Spinner(ChangeListener listener)
    {
        this.Peso1000Spn.addChangeListener(listener);
    }
    
    public void setBuy1Listener(ActionListener listener)
    {
        this.buy1.addActionListener(listener);
    }
    
    public void setBuy2Listener(ActionListener listener)
    {
        this.buy2.addActionListener(listener);
    }
    
    public void setBuy3Listener(ActionListener listener)
    {
        this.buy3.addActionListener(listener);
    }
    
    public void setBuy4Listener(ActionListener listener)
    {
        this.buy4.addActionListener(listener);
    }
    
    public void setBuy5Listener(ActionListener listener)
    {
        this.buy5.addActionListener(listener);
    }
    
    public void setBuy6Listener(ActionListener listener)
    {
        this.buy6.addActionListener(listener);
    }
    
    public void setBuy7Listener(ActionListener listener)
    {
        this.buy7.addActionListener(listener);
    }
    
    public void setBuy8Listener(ActionListener listener)
    {
        this.buy8.addActionListener(listener);
    }
    
    public void setConfirmListener(ActionListener listener)
    {
        this.confirm.addActionListener(listener);
    }
    
    public void setCancelListener(ActionListener listener)
    {
        this.cancel.addActionListener(listener);
    }
    
    public JSpinner getPeso1Spn()
    {
        return this.Peso1Spn;
    }
    
    public JSpinner getPeso5Spn()
    {
        return this.Peso5Spn;
    }
    
    public JSpinner getPeso20Spn()
    {
        return this.Peso20Spn;
    }
    
    public JSpinner getPeso50Spn()
    {
        return this.Peso50Spn;
    }
    
    public JSpinner getPeso100Spn()
    {
        return this.Peso100Spn;
    }
    
    public JSpinner getPeso500Spn()
    {
        return this.Peso500Spn;
    }
    
    public JSpinner getPeso1000Spn()
    {
        return this.Peso1000Spn;
    }
    
    public JLabel getVMName()
    {
        return this.vmName;
    }
    
    public JLabel getItem1Name()
    {
        return this.item1Name;
    }
    
    public JLabel getItem1Price()
    {
        return this.item1Price;
    }
    
    public JLabel getItem1Cal()
    {
        return this.item1Cal;
    }
    
    public JLabel getItem2Name()
    {
        return this.item2Name;
    }
    
    public JLabel getItem2Price()
    {
        return this.item2Price;
    }
    
    public JLabel getItem2Cal()
    {
        return this.item2Cal;
    }
    
    public JLabel getItem3Name()
    {
        return this.item3Name;
    }
    
    public JLabel getItem3Price()
    {
        return this.item3Price;
    }
    
    public JLabel getItem3Cal()
    {
        return this.item3Cal;
    }
    
    public JLabel getItem4Name()
    {
        return this.item4Name;
    }
    
    public JLabel getItem4Price()
    {
        return this.item4Price;
    }
    
    public JLabel getItem4Cal()
    {
        return this.item4Cal;
    }
    
    public JLabel getItem5Name()
    {
        return this.item5Name;
    }
    
    public JLabel getItem5Price()
    {
        return this.item5Price;
    }
    
    public JLabel getItem5Cal()
    {
        return this.item5Cal;
    }
    
    public JLabel getItem6Name()
    {
        return this.item6Name;
    }
    
    public JLabel getItem6Price()
    {
        return this.item6Price;
    }
    
    public JLabel getItem6Cal()
    {
        return this.item6Cal;
    }
    
    public JLabel getItem7Name()
    {
        return this.item7Name;
    }
    
    public JLabel getItem7Price()
    {
        return this.item7Price;
    }
    
    public JLabel getItem7Cal()
    {
        return this.item7Cal;
    }
    
    public JLabel getItem8Name()
    {
        return this.item8Name;
    }
    
    public JLabel getItem8Price()
    {
        return this.item8Price;
    }
    
    public JLabel getItem8Cal()
    {
        return this.item8Cal;
    }
    
    public JLabel getTotalCostLbl()
    {
        return this.TotalCostLbl;
    }
    
    public JLabel getTotalPaymentLbl()
    {
        return this.TotalPaymentLbl;
    }
    
    public JButton getCancelButton()
    {
        return this.cancel;
    }
    
    public JLabel getTotalCalLbl()
    {
        return this.Receipt1;
    }
    
    public JButton getBuy1()
    {
        return this.buy1;
    }
    
    public JButton getBuy2()
    {
        return this.buy2;
    }
    
    public JButton getBuy3()
    {
        return this.buy3;
    }
    
    public JButton getBuy4()
    {
        return this.buy4;
    }
    
    public JButton getBuy5()
    {
        return this.buy5;
    }
    
    public JButton getBuy6()
    {
        return this.buy6;
    }
    
    public JButton getBuy7()
    {
        return this.buy7;
    }
    
    public JButton getBuy8()
    {
        return this.buy8;
    }
    
    public JLabel getOrderHistory()
    {
        return this.orderHistory;
    }
    
    public JLabel getOrderLbl()
    {
        return this.orderLbl;
    }
    
    public JDialog getNotEnoughPaymentError()
    {
        return this.NotEnoughPaymentError;
    }
    
    public JDialog getNoChangeError()
    {
        return this.NoChangeError;
    }
    
    public JDialog getItemDispensedMsg()
    {
        return this.ItemDispensedMsg;
    }
    
    public JLabel getReceiptLbl()
    {
        return this.Receipt;
    }
    
    public void closeBuyButtons()
    {
        this.buy1.setVisible(false);
        this.buy2.setVisible(false);
        this.buy3.setVisible(false);
        this.buy4.setVisible(false);
        this.buy5.setVisible(false);
        this.buy6.setVisible(false);
        this.buy7.setVisible(false);
        this.buy8.setVisible(false);
    }
    
    public void openBuyButtons()
    {
        this.buy1.setVisible(true);
        this.buy2.setVisible(true);
        this.buy3.setVisible(true);
        this.buy4.setVisible(true);
        this.buy5.setVisible(true);
        this.buy6.setVisible(true);
        this.buy7.setVisible(true);
        this.buy8.setVisible(true);
    }
    
    public void resetMoneySpinners()
    {
        this.Peso1Spn.setValue(0);
        this.Peso5Spn.setValue(0);
        this.Peso20Spn.setValue(0);
        this.Peso50Spn.setValue(0);
        this.Peso100Spn.setValue(0);
        this.Peso500Spn.setValue(0);
        this.Peso1000Spn.setValue(0);
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JDialog ItemDispensedMsg;
    private javax.swing.JDialog NoChangeError;
    private javax.swing.JDialog NotEnoughPaymentError;
    private javax.swing.JSpinner Peso1000Spn;
    private javax.swing.JSpinner Peso100Spn;
    private javax.swing.JSpinner Peso1Spn;
    private javax.swing.JSpinner Peso20Spn;
    private javax.swing.JSpinner Peso500Spn;
    private javax.swing.JSpinner Peso50Spn;
    private javax.swing.JSpinner Peso5Spn;
    private javax.swing.JLabel Receipt;
    private javax.swing.JLabel Receipt1;
    private javax.swing.JLabel TotalCostLbl;
    private javax.swing.JLabel TotalPaymentLbl;
    private javax.swing.JButton buy1;
    private javax.swing.JButton buy2;
    private javax.swing.JButton buy3;
    private javax.swing.JButton buy4;
    private javax.swing.JButton buy5;
    private javax.swing.JButton buy6;
    private javax.swing.JButton buy7;
    private javax.swing.JButton buy8;
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JPanel item1;
    private javax.swing.JLabel item1Cal;
    private javax.swing.JLabel item1Name;
    private javax.swing.JLabel item1Price;
    private javax.swing.JPanel item2;
    private javax.swing.JLabel item2Cal;
    private javax.swing.JLabel item2Name;
    private javax.swing.JLabel item2Price;
    private javax.swing.JPanel item3;
    private javax.swing.JLabel item3Cal;
    private javax.swing.JLabel item3Name;
    private javax.swing.JLabel item3Price;
    private javax.swing.JPanel item4;
    private javax.swing.JLabel item4Cal;
    private javax.swing.JLabel item4Name;
    private javax.swing.JLabel item4Price;
    private javax.swing.JPanel item5;
    private javax.swing.JLabel item5Cal;
    private javax.swing.JLabel item5Name;
    private javax.swing.JLabel item5Price;
    private javax.swing.JPanel item6;
    private javax.swing.JLabel item6Cal;
    private javax.swing.JLabel item6Name;
    private javax.swing.JLabel item6Price;
    private javax.swing.JPanel item7;
    private javax.swing.JLabel item7Cal;
    private javax.swing.JLabel item7Name;
    private javax.swing.JLabel item7Price;
    private javax.swing.JPanel item8;
    private javax.swing.JLabel item8Cal;
    private javax.swing.JLabel item8Name;
    private javax.swing.JLabel item8Price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel orderHistory;
    private javax.swing.JLabel orderLbl;
    private javax.swing.JLabel ordertxt;
    private javax.swing.JLabel vmName;
    // End of variables declaration//GEN-END:variables
}
